# Site settings
title: One Piece 
header-img: img/home-bg.jpg
email: bill.quanquan@gmail.com
description: "talk is cheap, show me the code"
host: "127.0.0.1"
baseurl: ""
url: "http://doublequan.com"
github_username:  doublequan
zhihu_username: 

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","tmp","unless"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
